### ISSUE TITLE
GUDHI does not installs in the NVIDIA-supplied containers

### ISSUE THREAD

**Issue by oleg-kachan** [GUDHI/gudhi-devel#954]
I'm using the [latest](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-08.html) NVIDIA-supplied container based on Ubuntu 22.04, Python 3.10, G++ 11.4.0, CMake 3.22.1, and is unable to install GUDHI via pip, getting the following message

```
pip install gudhi
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting gudhi
  Downloading gudhi-3.8.0rc1.tar.gz (526 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 47, in <module>
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 990, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 825, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-f7e46cn4/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 119, in nonempty
          raise ValueError(error_msg)
      ValueError: 'D:/a/gudhi-devel/gudhi-devel/src/python/gudhi/off_utils.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by mglisse** [comment]
Could you show the output of `pip debug --verbose`? And maybe `pip install -vvv gudhi`. Building from source using pip does not work, but if you are using an x86_64 cpu (?) we should have a binary available.

**Comment by VincentRouvreau** [comment]
No answer from the user in 2 years. I am closing the issue
