### ISSUE TITLE
Some tests are sometime infinite or failing

### ISSUE THREAD

**Issue by DavidLapous** [GUDHI/gudhi-devel#961]
Some tests are (sometimes) failing on my laptop, i.e., I have to rerun `ctest` multiple times to get a 100% pass.
For these few example below, the behavior is undefined : either pass (~50% times) or segfaults or never finishes.
Typically : `***Exception: Illegal` or `Subprocess aborted***Exception`.
Some test that I've seen fail (may be non exhaustive)
 - `Delaunay_complex_Epeck_dynamic_test_unit` 
 - `Weighted_periodic_alpha_complex_3d_test_unit`
 - `Zero_weighted_alpha_complex_static_test_unit`
 - `Periodic_alpha_complex_3d_test_unit`
 
**My specs :**
 - **Software** 
My compiler (clang 15.0.7), boost, tbb, cgal (5.6), python libraries and everything else come from the conda-forge repo. And the c++ compiler used is the c++ compiler provided by the `compilers` package (what is used to compile every conda-forge package).
 - **Hardware**
M1 macbook air, on Ventura 13.5.2

As cgal was recently updated to the 5.6 version, and the error are all linked to alpha triangulation, my first guess would be in that direction.

Not really useful log : 

 ```
 Running 1 test case...
*****************************************************************************************************unknown location:0: fatal error: in "Delaunay_complex_exact_kernel_dynamic_simplices_comparison": memory access violation at address: 0x16b81c000: invalid permissions
gudhi-devel/src/Alpha_complex/test/Delaunay_complex_unit_test.h:37: last checkpoint
 ```
```
Running 1 test case...
*****************************************************************************************************unknown location:0: fatal error: in "Delaunay_complex_exact_kernel_static_simplices_comparison": memory access violation at address: 0x168ea7ff0: invalid permissions
gudhi-devel/src/Alpha_complex/test/Delaunay_complex_unit_test.h:37: last checkpoint
```
 
 ```
 Running 1 test case...
unknown location:0: fatal error: in "Zero_weighted_alpha_complex_static": memory access violation at address: 0x16fd3c000: invalid permissions
gudhi-devel/src/Alpha_complex/test/Zero_weighted_alpha_complex_unit_test.h:41: last checkpoint
```

The cmake log :
```
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_PYTHON=ON -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_BENCHMARK=OFF -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=OFF  ..
-- GUDHI version : 3.9.0a1
-- boost include dirs:/Users/dloiseau/micromamba/envs/python/include
-- boost library dirs:/Users/dloiseau/micromamba/envs/python/lib
-- Using header-only CGAL
-- Targeting Unix Makefiles
-- Using /Users/dloiseau/micromamba/envs/python/bin/arm64-apple-darwin20.0.0-clang++ compiler.
-- Running in macOS DARWIN_VERSION=22
-- Boost include dirs: /Users/dloiseau/micromamba/envs/python/include
-- Boost libraries:
-- CGAL version: 5.6.
-- Build type: Release
-- USING CXXFLAGS = '-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/dloiseau/micromamba/envs/python/include -O3 -DNDEBUG'
-- USING EXEFLAGS = '-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/dloiseau/micromamba/envs/python/lib -L/Users/dloiseau/micromamba/envs/python/lib '
++ TBB version 2021.10.0 found in /Users/dloiseau/micromamba/envs/python/lib - includes in /Users/dloiseau/micromamba/envs/python/include
diff found in /usr/bin/diff
CMake Warning (dev) at src/cmake/modules/GUDHI_third_party_libraries.cmake:130 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

++ Python module cython - Version 3.0.2  found
++ Python module pytest - Version 7.4.2  found
++ Python module matplotlib - Version 3.7.1  found
++ Python module numpy - Version 1.25.2  found
++ Python module scipy - Version 1.11.2  found
++ Python module sphinx - Version 7.2.6  found
++ Python module sklearn - Version 1.3.0  found
++ Python module ot - Version 0.9.0  found
++ Python module pybind11 - Version 2.11.1  found
++ Python module torch - Version 2.0.0  found
++ Python module pykeops - Version [KeOps] Warning : omp.h header is not in the path, disabling OpenMP. [KeOps] Warning : Cuda libraries were not detected on the system ; using cpu only mode 2.1.2  found
PYTHON_MODULE_NAME = eagerpy
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION =
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'eagerpy'

PYTHON_MODULE_NAME = hnswlib
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hnswlib'

PYTHON_MODULE_NAME = tensorflow
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION =
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'

PYTHON_MODULE_NAME = sphinx_paramlinks
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION =
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx_paramlinks'

PYTHON_MODULE_NAME = pydata_sphinx_theme
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION =
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pydata_sphinx_theme'

++ Python module networkx - Version 3.1  found
++ Release compilation flags are: -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/dloiseau/micromamba/envs/python/include -Wall -pedantic -O3 -DNDEBUG
++ GUDHI_SUB_DIRECTORIES list is:";test"
++ GudhUI will not be compiled because QGLViewer is not found
++ /Users/dloiseau/micromamba/envs/python/lib/libgmp.dylib => UNIX_LIB_FILE_NAME = gmp
** Add gmp /Users/dloiseau/micromamba/envs/python/lib
++ /Users/dloiseau/micromamba/envs/python/lib/libgmpxx.dylib => UNIX_LIB_FILE_NAME = gmpxx
** Add gmpxx /Users/dloiseau/micromamba/envs/python/lib
++ /Users/dloiseau/micromamba/envs/python/lib/libmpfr.dylib => UNIX_LIB_FILE_NAME = mpfr
** Add mpfr /Users/dloiseau/micromamba/envs/python/lib
++ /Users/dloiseau/micromamba/envs/python/lib/libtbb.12.10.dylib => UNIX_LIB_FILE_NAME = tbb
++ /Users/dloiseau/micromamba/envs/python/lib/libtbbmalloc.2.10.dylib => UNIX_LIB_FILE_NAME = tbbmalloc
** Add tbb /Users/dloiseau/micromamba/envs/python/lib
++ Python documentation module will not be compiled because sphinxcontrib-paramlinks was not found
++ GUDHI_MODULES list is:"common;Alpha_complex;Bitmap_cubical_complex;Bottleneck_distance;Collapse;Contraction;Coxeter_triangulation;Cech_complex;Hasse_complex;Persistence_representations;Persistent_cohomology;Rips_complex;Simplex_tree;Skeleton_blocker;Spatial_searching;Subsampling;Tangential_complex;Toplex_map;Witness_complex;Nerve_GIC;python"
++ GUDHI_MISSING_MODULES list is:"GudhUI;python-documentation;cpp-documentation"
-- Configuring done (5.0s)
-- Generating done (0.2s)
-- Build files have been written to: /Users/dloiseau/Downloads/temp/gudhi-devel/build
```

**Comment by mglisse** [comment]
To try to reproduce, I connected to the public machine gcc104.fsffrance.org (cpu M1, MacOSX 12.6), installed mambaforge and a bunch of packages
```
# Name                    Version                   Build  Channel
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h00df5ed_4    conda-forge
brotli-python             1.1.0           py310h1253130_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
c-compiler                1.6.0                hd291e01_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cctools                   973.0.1             hd1ac623_14    conda-forge
cctools_osx-arm64         973.0.1             h2a25c60_14    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_3    conda-forge
cgal-cpp                  5.6                  hed76ac3_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
clang                     15.0.7               hce30654_3    conda-forge
clang-15                  15.0.7          default_h5dc8d65_3    conda-forge
clang_osx-arm64           15.0.7               h77e971b_3    conda-forge
clangxx                   15.0.7          default_h610c423_3    conda-forge
clangxx_osx-arm64         15.0.7               h768a7fd_3    conda-forge
cmake                     3.27.5               h1c59155_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
compiler-rt               15.0.7               hf8d1dfb_1    conda-forge
compiler-rt_osx-arm64     15.0.7               hf8d1dfb_1    conda-forge
compilers                 1.6.0                hce30654_0    conda-forge
conda                     23.7.4          py310hbe9552e_0    conda-forge
conda-libmamba-solver     23.7.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3          py310hdd3b5e7_0    conda-forge
cxx-compiler              1.6.0                h1995070_0    conda-forge
eigen                     3.4.0                h1995070_0    conda-forge
fmt                       10.1.1               h1995070_0    conda-forge
fortran-compiler          1.6.0                h5a50232_0    conda-forge
gfortran                  12.3.0               h1ca8e4b_1    conda-forge
gfortran_impl_osx-arm64   12.3.0               hbbb9e1e_1    conda-forge
gfortran_osx-arm64        12.3.0               h57527a5_1    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
isl                       0.25                 h9a09cb3_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310hbe9552e_2    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
ld64                      609                 h89fa09d_14    conda-forge
ld64_osx-arm64            609                 hc4dc95b_14    conda-forge
libarchive                3.6.2                h82b9b87_1    conda-forge
libclang-cpp15            15.0.7          default_h5dc8d65_3    conda-forge
libcurl                   8.3.0                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran-devel_osx-arm64 12.3.0               hc62be1c_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libllvm15                 15.0.7               h504e6bf_3    conda-forge
libmamba                  1.5.1                h6089622_0    conda-forge
libmambapy                1.5.1           py310ha8cccbf_0    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libsolv                   0.7.24               ha614eb4_4    conda-forge
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libuv                     1.46.0               hb547adb_0    conda-forge
libxml2                   2.11.5               h25269f3_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
llvm-tools                15.0.7               h504e6bf_3    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
mamba                     1.5.1           py310ha5d4528_0    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.0                he09a6ba_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.2                h53f4e23_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h8e9501a_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reproc                    14.2.4               h1a8c8d9_0    conda-forge
reproc-cpp                14.2.4               hb7217d7_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rhash                     1.4.4                hb547adb_0    conda-forge
ruamel.yaml               0.17.32         py310h2aa6e3c_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h8e9501a_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tbb                       2021.10.0            h1995070_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml-cpp                  0.7.0                hb7217d7_2    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstandard                 0.19.0          py310h8e9501a_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```
Did a (recursive) git clone of gudhi-devel, created a subdirectory build/, `cmake -DCMAKE_BUILD_TYPE=Release ..`, `make -j4`, `make -j4 test`, and all the tests (including the 4 you mention) pass. I re-ran the last command a few times, but the tests always pass. The weighted-periodic one takes ~8s, by far the longest. CMake shows
```
$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/glisse/mambaforge/bin/arm64-apple-darwin20.0.0-clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/glisse/mambaforge/bin/arm64-apple-darwin20.0.0-clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GUDHI version : 3.9.0a1
-- boost include dirs:/Users/glisse/mambaforge/include
-- boost library dirs:/Users/glisse/mambaforge/lib
-- Found GMP: /Users/glisse/mambaforge/lib/libgmp.dylib  
-- Found GMPXX: /Users/glisse/mambaforge/lib/libgmpxx.dylib  
-- Using header-only CGAL
-- Targeting Unix Makefiles
-- Using /Users/glisse/mambaforge/bin/arm64-apple-darwin20.0.0-clang++ compiler.
-- Running in macOS DARWIN_VERSION=21
-- Found MPFR: /Users/glisse/mambaforge/lib/libmpfr.dylib  
-- Found Boost: /Users/glisse/mambaforge/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.66")  
-- Boost include dirs: /Users/glisse/mambaforge/include
-- Boost libraries:    
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- CGAL version: 5.6.
-- Build type: Release
-- USING CXXFLAGS = '-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/glisse/mambaforge/include -O3 -DNDEBUG'
-- USING EXEFLAGS = '-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/glisse/mambaforge/lib -L/Users/glisse/mambaforge/lib '
-- Could NOT find TBB (missing: TBB_DIR)
-- Found Eigen3: /Users/glisse/mambaforge/include/eigen3 (found suitable version "3.4.0", minimum required is "3.1.0") 
diff found in /usr/bin/diff
CMake Warning (dev) at src/cmake/modules/GUDHI_third_party_libraries.cmake:130 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /Users/glisse/mambaforge/bin/python (found version "3.10.12") 
PYTHON_MODULE_NAME = cython
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cython'

PYTHON_MODULE_NAME = pytest
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytest'

PYTHON_MODULE_NAME = matplotlib
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'

PYTHON_MODULE_NAME = numpy
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

PYTHON_MODULE_NAME = scipy
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

PYTHON_MODULE_NAME = sphinx
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx'

PYTHON_MODULE_NAME = sklearn
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sklearn'

PYTHON_MODULE_NAME = ot
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ot'

PYTHON_MODULE_NAME = pybind11
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'

PYTHON_MODULE_NAME = torch
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

PYTHON_MODULE_NAME = pykeops
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pykeops'

PYTHON_MODULE_NAME = eagerpy
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'eagerpy'

PYTHON_MODULE_NAME = hnswlib
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hnswlib'

PYTHON_MODULE_NAME = tensorflow
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

PYTHON_MODULE_NAME = sphinx_paramlinks
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx_paramlinks'

PYTHON_MODULE_NAME = pydata_sphinx_theme
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pydata_sphinx_theme'

PYTHON_MODULE_NAME = networkx
       - PYTHON_MODULE_RESULT = 1
       - PYTHON_MODULE_VERSION = 
       - PYTHON_MODULE_ERROR = Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'networkx'

-- Checking to see if CXX compiler accepts flag -Wall
-- Checking to see if CXX compiler accepts flag -Wall - yes
++ Release compilation flags are: -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/glisse/mambaforge/include -Wall -pedantic -O3 -DNDEBUG
++ GUDHI_SUB_DIRECTORIES list is:";test;utilities"
++ GudhUI will not be compiled because Qt5 COMPONENTS Widgets Xml OpenGL are not found
++ Python module will not be compiled because numpy and/or cython and/or pybind11 was/were not found
++ GUDHI_MODULES list is:"common;Alpha_complex;Bitmap_cubical_complex;Bottleneck_distance;Collapse;Contraction;Coxeter_triangulation;Cech_complex;Hasse_complex;Persistence_representations;Persistent_cohomology;Rips_complex;Simplex_tree;Skeleton_blocker;Spatial_searching;Subsampling;Tangential_complex;Toplex_map;Witness_complex;Nerve_GIC"
++ GUDHI_MISSING_MODULES list is:"GudhUI;python;cpp-documentation"
-- Configuring done (1.7s)
-- Generating done (0.3s)
-- Build files have been written to: /Users/glisse/gudhi-devel/build
```
The OSX version is not the same, and the cmake outputs have a surprising number of seemingly minor differences, but I don't immediately see what may explain the different behavior on your computer.
